services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://host.docker.internal:3306/keycloak?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root

    ports:
      - "8180:8080"