spring.application.name=barbearia-api

spring.datasource.url=jdbc:mysql://10.35.238.4:3306/barbearia?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=notebook
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://10.35.224.215:5001/realms/barbearia-ph

keycloak.client-id=barbearia-backend
keycloak.client-secret=qDYFwW69SCSzvoqHxGZZ6avQAm2AqVla
keycloak.token-url=http://10.35.224.215:5001/realms/barbearia-ph/protocol/openid-connect/token

server.port=8080